apiVersion: v1
kind: PersistentVolume
metadata:
  name: gismap-gis-pv-volume
  namespace: gis
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/mnt/data/gismap"
